In [81]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [82]:
df = pd.read_csv('train.txt', sep=';',header=None,names=['text','emotions'])

In [83]:
df.shape

(16000, 2)

In [84]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [85]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [86]:
df.drop_duplicates()

                                                    text emotions
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[15999 rows x 2 columns]

In [87]:
df['emotions'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [88]:
unique_emotions = df['emotions'].unique() 
i =0
emotion_numbers = {}
for emotion in unique_emotions: 
    emotion_numbers[emotion]=i
    i+=1

In [89]:
print(emotion_numbers)

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

# 1. Convert everyting to lower case

In [90]:
df['text'] = df['text'].apply(lambda x : x.lower())

# 2. Remove punctuation (not req in ML can be used in DL)

In [91]:
import string 

def remove_punc(txt): 
    return txt.translate(str.maketrans('','',string.punctuation))

In [92]:
df['text'] = df['text'].apply(remove_punc)

# 3. Remove numbers

In [93]:
def remove_nums(txt): 
    new = ""
    for i in txt:
        if not i.isdigit(): 
            new = new + i
    return new

In [94]:
df['text'] = df['text'].apply(remove_nums)

# 4. Remove URLs/Links

# 5. Remove HTML tags (if data is scrapped)

# 6. Remove Emojis & Special characters

In [95]:
def remove_emojis(txt): 
    new = ""
    for i in txt:
        if i.isascii(): 
            new = new + i
    return new

df['text'] = df['text'].apply(remove_emojis)

# 7. Remove stop keywords: "is", "was", "and", "in" (not req in ML can be used in DL)

In [96]:
import nltk

In [97]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [98]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/shikshakkumar/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/shikshakkumar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [99]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [101]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [110]:
def remove_stopwords(txt): 
    words = txt.split() # do this if word_tokenize not working
    cleaned = []
    for i in words: 
        if not i in stop_words: 
            cleaned.append(i)
    return ' '.join(cleaned)

In [111]:
df['text'] = df['text'].apply(remove_stopwords)

In [112]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'